# Generated by Django 4.0 on 2021-12-24 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='page_number',
            field=models.IntegerField(blank=True, default=123),
        ),
        migrations.AddField(
            model_name='product',
            name='publisher',
            field=models.CharField(blank=True, default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='reprint',
            field=models.CharField(blank=True, default='None', max_length=255),
        ),
    ]
